### ISSUE TITLE
Revisar el README del proyecto, ya subí la descripción de mi parte del proyecto también. 

### ISSUE THREAD

**Issue by JorgeUmcc** [JorgeUmcc/ProyectoParqueo.Code#2]
En el README ya se encuentra la descripción del proyecto y enlaces para ver el uml y las partes del programa que realicé
@yosbel-penate

**Comment by yosbel-penate** [comment]
Lo reviso y evalúo

**Comment by yosbel-penate** [comment]
Por lo general me gusta como lo estas organizando se ve bien, te tengo estas notas:

--->Debes hacer una descripción por pasos del problema en si que estas resolviendo, y los pasos que van a seguir cada uno de los actores de tu parte del negocio, explicando paso por paso lo que hace cada uno de ellos en tu aplicación o al menos en la parte que te toca, la parte que te tocó implementar debes contar con una descripción lo que hace la persona que va a trabajar con tu aplicación. Ejemplo: los actores de mi modulo son la secretaria, el administrador, la funcionaria, 
-La secretaria es la encargada de dar entrada a los productos en el almacén, cuando un camión llega se descargan los productos la secretaria hace un vale por cada producto y introduce al sistema el nombre del producto, el peso, si es un producto de tal tipo se toma tal tal dato ext

---> Si vas a hacer referencia en el texto a una imagen usa el tag que te puse esta renderizara la imagen. 

---> si vas a hacer referencia a código hazlo como te puse en el ejemplo, usa este tutorial para saber cómo se hace:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

Solo concéntrate en hacer tu parte, es una tarea individual, recuérdale a tus miembros que para tener derecho a la primera vuelta de exposiciones se debe aprobar el proyecto propuesto, esta descripción debió ser entregada esta semana que ha pasado por tanto el que no te la haya dado está atrasado, el texto neto sin contar imágenes o diagramas debe ser igual o superior a 2 cuartillas en hojas de tamaño de página carta y como letra arial 12. Describiendo los procesemos que ocurren en el negocio solo con eso hay material suficiente para cumplir esta parte.

**Comment by JorgeUmcc** [comment]
Ok voy a editar el README entonces para que esté como debe estar, cualquier duda le preguntaré
